console.log("valores booleanos")
console.log(true)
console.log(false)
console.log(5>2)
console.log(2>5)
console.log(2<=2)
console.log(3>=6)
console.log("2" == 2)
console.log(2 === "2")
console.log(2 === 2)

